title: Line Flows and Line Losses
description: This project calculates the line flows and line losses with the given data

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache

relative_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true


mermaid:
  enable: true
  version: 11.4.1

mathjax:
  enable: true

usemathjax: true
